studentCREATE DATABASE tkd;

USE tkd;

DROP TABLE student;

CREATE TABLE student (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(32) NOT NULL,
  birth_date DATE NOT NULL,
  gender VARCHAR(30) NOT NULL,
  belt VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE competition (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	competition_type VARCHAR(30) NOT NULL,
	category VARCHAR(50) NOT NULL,
	result VARCHAR(20) NOT NULL,
	event_date DATE NOT NULL,
	student_id BIGINT(20) NOT NULL,
	FOREIGN KEY (student_id) REFERENCES student(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;tkd