studentCREATE DATABASE tkd;

USE tkd;

CREATE TABLE student (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(32) NOT NULL,
  birth_date DATE NOT NULL,
  gender VARCHAR(30) NOT NULL,
  belt VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE training (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  training_type VARCHAR(30) NOT NULL,
  training_date DATE NOT NULL,
  student_id BIGINT(20) NOT NULL,
  CONSTRAINT fk_training_student
    FOREIGN KEY (student_id) REFERENCES student(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;